### ISSUE TITLE
「Invalid default value for 'update_date'」が発生する

### ISSUE THREAD

**Issue by ghost** [retas-seven/entrec#2]
@retas-seven 
https://github.com/retas-seven/entrec/blob/9d278dd4977d8f438ec213052baab4d456d57fa8/ddl/create.sql#L19

環境によっては、timestampのデフォルト値として'0000-00-00 00:00:00'が使えないようです。
sql_modeを変更するか、日付として妥当な値に変更したほうが良さそうです。

こちらのURLの事象と酷似しています。
https://stackoverflow.com/questions/9192027/invalid-default-value-for-create-date-timestamp-field

**Comment by retas-seven** [comment]
'0000-00-00 00:00:00'からCURRENT_TIMESTAMPに変更しました。
